title: Oppna-Program
description: Open source development for public health care in Vastra Gotalandsregionen, Sweden
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
